### ISSUE TITLE
Not playing and question about Upnp

### ISSUE THREAD

**Issue by arjunmenon** [trishika/DroidUPnP#68]
Hey
On a Redmi4A with Android 6

The app is not playing any mp3 when clicked. It shows all files but does not play.
Long pressing it shows options to play it from some other app.

I would like to ask about the Upnp behaviour.
When you have to stream audio, does this mean the DroidUpnp becomes a server? A control point will show everything, audio list, control playback, etc.
But to play music, stream them to the Upnp renderer does it have to become a server?

**Comment by m3sv** [comment]
This could be a rendrer issue, have you tried streaming mp3 from another UPnP app?

**Comment by trishika** [comment]
Yes probably renderer issue.
DroidUpnp does not become a server. It just provided the URL of the file on the content provider to the renderer.

**Comment by arjunmenon** [comment]
Hey @trishika  @m3sv 
Yeah I have been using Bubble upnp. It works from there. I can confirm it is not a renderer issue because I tried streaming from my own custom Tabris js app as well. It works from curl as well.

**Comment by m3sv** [comment]
@arjunmenon hm, I'm pretty sure it's an issue of a particular renderer. Have you tried it with the same file across all clients? You can launch DroidUPnP and check from logs that it provides mp3 file just fine. Right now I can't try it, but I'm pretty sure that the last time I checked (including Bubble) I couldn't stream mp3 files from any of UPnP clients to a particular renderer. All of them worked fine with Kodi, though. I'll try and update on this tomorrow.
